name: DarkyenusBuild
version: 1.4-SNAPSHOT
main: darkyenus.plugin.build.DarkyenusBuild
authors: [Darkyen]
commands:
  build:
    description: Create new build tool.
    aliases: [b, create, bs, buildsettings]
    permission: darkyenusbuild
  darkyenusbuild:
    aliases: [dbld, dbuild]
    usage: /dbld [selectors/filters/actions/...]
    description: Darkyenus Build plugin info
  tool:
    description: View settings of your tool or change name
    usage: /tool [New Name]
    permission: darkyenusbuild
permissions:
  darkyenusbuild:
    description: Allows you to use DarkyenusBuild
    default: op